use list instead of extract

diff --git a/packages/toolbox-core/package.cloudbuild.yaml b/packages/toolbox-core/package.cloudbuild.yaml
--- a/packages/toolbox-core/package.cloudbuild.yaml
+++ b/packages/toolbox-core/package.cloudbuild.yaml
@@ -37,9 +37,8 @@ steps:
     args:
       - '-c'
       - |
-        tar -xf *.tgz
-        if [ ! -f package/build/esm/index.js ]; then echo "Missing esm index"; exit 1; fi
-        if [ ! -f package/build/cjs/index.js ]; then echo "Missing cjs index"; exit 1; fi
+        if ! tar -tf *.tgz | grep -q "package/build/esm/index.js"; then echo "Missing esm index"; exit 1; fi
+        if ! tar -tf *.tgz | grep -q "package/build/cjs/index.js"; then echo "Missing cjs index"; exit 1; fi
 
 options:
   logging: CLOUD_LOGGING_ONLY
